config/routes.rb
MSampleApp::Application.routes.draw do
  
  devise_for :users
  resources :users, :except => [:new, :create] do # Routes for the users controller
    resources :microposts,  :only => [:index, :show]
    member do
      get :following, :followers
    end
  end
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match 'about' => 'pages#about'
  match 'help' => 'pages#help'
  
  root :to => "pages#home" # Setting up the root route
  

end

app/models/micropost.rb
class Micropost
  include Mongoid::Document
  include Mongoid::Timestamps::Created # Track the timestamps but only the created_at field
  field :content
  field :user_id, :type => Integer
  
  attr_accessible :content
  
  belongs_to :user
  
  validates :content, :presence => true, :length => {:maximum => 140}
  validates :user_id, :presence => true
  
  default_scope desc(:created_at)
  
  def self.from_users_followed_by(user)
    any_in(:user_id => user.following_relations.map(&:followed_id) << user.id)
    # any_in(:user_id => user.following.push(user).map(&:to_param)) #- Shorter syntax, but less efficient
  end
end

app/models/relationship.rb
class Relationship
  include Mongoid::Document
  include Mongoid::Timestamps::Created # Track the timestamps but only the created_at field
  field :follower_id, :type => Integer
  field :followed_id, :type => Integer
  # index on both columns and also includes a composite index that enforces uniqueness of pairs
  index([[:follower_id, Mongo::ASCENDING], [:followed_id, Mongo::ASCENDING]], :unique => true)
  
  attr_accessible :followed_id
  
  belongs_to :follower, :class_name => "User", :inverse_of => :following_relations
  belongs_to :followed, :class_name => "User", :inverse_of => :followers_relations
  
  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created # Track the timestamps but only the created_at field
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  field :name
  field :admin, :type => Boolean
  
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :microposts, :dependent => :destroy # destroy associated microposts before_destroy
  has_many :following_relations, :class_name => "Relationship", :foreign_key => :follower_id, :inverse_of => :follower, :dependent => :destroy
  has_many :followers_relations, :class_name => "Relationship", :foreign_key => :followed_id, :inverse_of => :followed, :dependent => :destroy
  
  validates :name, :presence => true, :length   => { :maximum => 60 }
  validates_uniqueness_of :email, :case_sensitive => false
  
  scope :admin, where(:admin => true)
  
  paginates_per 30
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def toggle_admin!
    self.admin = !admin
    self.save!
  end
  
  # Methods for following/follower relationships
  def following
    #User.any_in(:_id => following_relations.collect {|rel| rel.followed_id})
    User.any_in(:_id => following_relations.map(&:followed_id))
  end
  
  def followers
    #User.any_in(:_id => followers_relations.collect {|rel| rel.follower_id})
    User.any_in(:_id => followers_relations.map(&:follower_id))
  end
  
  def following?(followed)
    following.include?(followed)
  end

  def follow!(followed)
    following_relations.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    following_relations.where(:followed_id => followed.id).first.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
    def redirect_back_or(path)
      redirect_to :back
      rescue ActionController::RedirectBackError
      redirect_to path
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  
  def index
    @user = User.find(params[:user_id])
    @feed_items = @user.feed.page(params[:page])
  end
  
  def show
    @feed_item = Micropost.find(params[:id])
  end
  
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end
  
  private

    def authorized_user
      # @micropost = current_user.microposts.where(:_id => params[:id]).first
      # redirect_to root_path if @micropost.nil?
      # We can just use the code below if we are comfortable with exceptions in ruby
      @micropost = current_user.microposts.find(params[:id])
    rescue
      redirect_to root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if user_signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.page(params[:page])
    end
  end

  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate_user!
  
  respond_to :html, :js
  
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_with @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_with @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  before_filter :admin_user, :only => [:destroy, :edit, :update]
  
  # GET /users
  # GET /users.xml
  def index
    @title = "User List"
    @users = User.order_by([:created_at, :asc]).page(params[:page]) # Order by created at date

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    @feed_items = @user.feed.page(params[:page])
    @title = @user.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
  
  # GET /users/1/following
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end
  
  # GET /users/1/followers
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @title = "Edit #{@user.name}"
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to(@user) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    User.find(params[:id]).destroy

    respond_to do |format|
      flash[:success] = "User deleted."
      format.html { redirect_to(users_path) }
      # format.html { redirect_to(users_path, :notice => "User deleted.") }
      format.xml  { head :ok }
    end
  end
  
  private
  
    def admin_user # Method to ensure that a user is an admin
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis.
  def title
    base_title = "Ben's Sample App"
    @title.nil? ? base_title : "#{base_title} | #{@title}"
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 36)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="bottom_rounded">
    <ul>
      <li><%= link_to "Home", :root %>
      <li><%= link_to "About", :about %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", :root %></li>
      <li><%= link_to "Help", :help %></li>
      <% unless user_signed_in? %>
      	<li><%= link_to "Sign in", new_user_session_path %></li>
      <% else %>
        <li><%= link_to "Users", users_path %></li>
      	<li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
      	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'form_helper' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title> <!-- Uses the title helper on application_helper.rb -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="top_rounded">
      	<% flash.each do |key, value| %>
	    	<div class="flash <%= key %>"><%= value %></div>
	    <% end %>
        <%= yield %>
      </section>
       <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
  <% if current_user == micropost.user %>
    <td>
      <%= link_to "delete", micropost, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => micropost.content %>
    </td>
  <% end %>
</tr>

app/views/microposts/index.html.erb
<h2><%= @user.name %></h2>
<%= render 'shared/feed' %>

app/views/microposts/show.html.erb
<%= render :partial => 'shared/individual_post', :locals => { :feed_item => @feed_item } %>

app/views/pages/_welcome.html.erb
<h1>Welcome to Ben's Sample App</h1>
<p>Welcome to the home page for Ben's Sample app.  This page will be improved as development progresses.</p>
<%= link_to "Sign up now!", new_user_registration_path, :class => "signup_button round" %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is a small sample app created for the purpose of demonstrating Rails 3 in conjunction with MongoDB using the mongoid gem.</p>
<p>The author's name is Ben Atkins.  You can find his website <a href="http://www.batkins.net/">here</a>.</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails by checking out of these resources:
  <ul>
  	<li><%= link_to "The official Ruby on Rails site", 'http://rubyonrails.org/' %></li>
  	<li><a href="http://railstutorial.org/book">Rails Tutorial book</a></li>
  	<li><%= link_to "Rails Tutorial help page", 'http://railstutorial.org/help '%></li>
  </ul>
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>
<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/relationships/create.js.erb
$("follow_form").update("<%= escape_javascript(render('users/unfollow')) %>")
$("followers").update('<%= pluralize(@user.followers.count, "follower") %>')

app/views/relationships/destroy.js.erb
$("follow_form").update("<%= escape_javascript(render('users/follow')) %>")
$("followers").update('<%= pluralize(@user.followers.count, "follower") %>')

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= paginate @feed_items %>
  <br/>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="micropost">
    <%= render :partial => 'shared/individual_post', :locals => { :feed_item => feed_item } %>
  </td>
  <% if current_user == feed_item.user %>
    <td>
      <%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => feed_item.content %>
    </td>
  <% end %>
</tr>

app/views/shared/_individual_post.html.erb
<span class="user">
  <%= link_to feed_item.user.name, feed_item.user %>
</span>
<span class="content"><%= wrap(feed_item.content) %></span>
<span class="post_timestamp">
  Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
</span>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content, :maxlength => 140 %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <span class="user_name">
    <%= link_to current_user.name, user_path(current_user) %>
  </span>
  <br/>
  <span class="microposts">
    <%= link_to pluralize(current_user.microposts.count, "micropost"), user_microposts_path(current_user) %>
  </span>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.following_relations.build(:followed_id => @user.id),
				:remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.eql?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.following_relations.where(:followed_id => @user.id).first,
             :html => { :method => :delete }, :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.name, user %></td>
  <td><%= user.email %></td>
  <% if current_user.admin? %>
	<td><%= link_to 'Edit', edit_user_path(user) %></td>
	<td><% unless user.admin? %>
		<%= link_to 'Delete', user, :confirm => 'Are you sure?', :method => :delete %>
	<% end %></td>
  <% end %>
</tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Listing users</h2>

<%= paginate @users %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <% if current_user.admin? %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>
<br/>

app/views/users/show.html.erb
<table class="profile">
  <tr>
    <td class="main">
      <h2><%= @user.name %></h2>
      <%= render 'follow_form' if user_signed_in? %>
      <%= render 'shared/feed' %>
    </td>
    <td class="sidebar round">
      <span><strong>Name</strong> <%= @user.name %></span><br/>
      <span><strong>URL</strong> <%= link_to user_path(@user), @user %></span><br/>
      <span><strong>Microposts</strong> <%= link_to @user.microposts.count, user_microposts_path(@user) %></span>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h2><%= @title %></h2>
      <% unless @users.empty? %>
        <table class="users">
        	<tbody>
          <%= render @users %>
          </tbody>
        </table>
        <%= paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>